services:
  backend:
    container_name: app_backend
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /app-backend
    command: dev
    volumes:
      - ./src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:${APP_PORT}"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 30s
  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - ${DB_PORT}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    restart: "always"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-ppassword",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    cap_add:
      - SYS_NICE
